### ISSUE TITLE
improve displaying of swarm hash

### ISSUE THREAD

**Issue by ligi** [efdevcon/devcon-website#180]
currently it can go outside the container which looks bad:

![image](https://user-images.githubusercontent.com/111600/200647923-0441796a-ea7b-4095-a7ca-65552659531f.png)

Also wondering if we directly should expose the swarm hash (not really sure end users should see hashes without asking for them)

**Comment by wslyvh** [comment]
Fixed

**Comment by ligi** [comment]
Is the fix rolled out? I am still seeing this:

![image](https://user-images.githubusercontent.com/111600/204468788-b455e608-78e8-43ff-b0b5-5dd3f4b49838.png)

**Comment by wslyvh** [comment]
Yes, it is deployed. Shouldn't be an issue, but can you do a hard-refresh to be sure?
If that doesn't help, can you share more info on browser/device/resolution as I'm unable to reproduce
